// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3rO7SDlDJa4AbDBqbwWLlPBxk8lSvqpY',
    appId: '1:991589986641:web:0a3d1d777ce4cf1ea12370',
    messagingSenderId: '991589986641',
    projectId: 'food-delivery-94ac6',
    authDomain: 'food-delivery-94ac6.firebaseapp.com',
    storageBucket: 'food-delivery-94ac6.firebasestorage.app',
    measurementId: 'G-12HMG4H7T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZVvj6k-8bPpjr6BtEBeS1cLpI_Gs0uo',
    appId: '1:991589986641:android:c0a84d1199c4cb8ea12370',
    messagingSenderId: '991589986641',
    projectId: 'food-delivery-94ac6',
    storageBucket: 'food-delivery-94ac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoO1Dv1pSOS5gk9LJhlCglG2BTQVE0Mo',
    appId: '1:991589986641:ios:037b2c0c8b149da4a12370',
    messagingSenderId: '991589986641',
    projectId: 'food-delivery-94ac6',
    storageBucket: 'food-delivery-94ac6.firebasestorage.app',
    iosClientId: '991589986641-v5i2grh37umsj82o16tctsv6nfqik4ei.apps.googleusercontent.com',
    iosBundleId: 'com.poeage.customerMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoO1Dv1pSOS5gk9LJhlCglG2BTQVE0Mo',
    appId: '1:991589986641:ios:037b2c0c8b149da4a12370',
    messagingSenderId: '991589986641',
    projectId: 'food-delivery-94ac6',
    storageBucket: 'food-delivery-94ac6.firebasestorage.app',
    iosClientId: '991589986641-v5i2grh37umsj82o16tctsv6nfqik4ei.apps.googleusercontent.com',
    iosBundleId: 'com.poeage.customerMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3rO7SDlDJa4AbDBqbwWLlPBxk8lSvqpY',
    appId: '1:991589986641:web:6f884d97c4c05b82a12370',
    messagingSenderId: '991589986641',
    projectId: 'food-delivery-94ac6',
    authDomain: 'food-delivery-94ac6.firebaseapp.com',
    storageBucket: 'food-delivery-94ac6.firebasestorage.app',
    measurementId: 'G-L8XQPYW71D',
  );
}
